### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by floatas** [Snow-Gremlin/Blackboard#25]
Hey there,

I'm unable to compile project, looks like this DLL is not included in the source:
![image](https://user-images.githubusercontent.com/7883111/135594923-f3e1c199-1c55-40aa-8d71-0d875d18b8ea.png)

Also, I noticed that you have some custom code formatting
![image](https://user-images.githubusercontent.com/7883111/135595007-431505f4-dba5-4d93-bce2-8d2657130ef9.png)
Do you use an extension to format code?

**Comment by Grant-Nelson** [comment]
Thank you for checking this out. Sorry I didn't notice this issue until now.

[`PetiteParser`](https://github.com/Grant-Nelson/PetiteParserCSharp) is one of my other repos. You're right, that dll should really be included better. However, even it that dll was fixed, this code wouldn't build yet because, as I said at the end of [README.md](https://github.com/Grant-Nelson/BlackboardCSharp/blob/main/README.md), "Currently the parser is being finished and is in a broken state". The broken parser isn't `PatiteParser` (which is in a good state) but the [BlackBoard Language Parser](https://github.com/Grant-Nelson/BlackboardCSharp/blob/main/Blackboard/Parser/Parser.cs) which relies on `PatiteParser`. Hacktoberfest kind of snuck up on me and I didn't get the Blackboard parser finished before October started, I'm [working to complete it](https://github.com/Grant-Nelson/BlackboardCSharp/issues/1) within about a week. 🤞

I normally use the builtin formatting from Visual Studio Express, however I will manually format lists like this, matrices, etc to make it easier to read. The way I think of it is, since most compilers don't care about formatting, formatters are just for human readability. So if it doesn't make it more readable then I'll manually format. Since this means I auto-run a formatter on `}` and `;` but not on save, if you find some code that needs formatting, feel free to do it, sometimes a bad formatted bit of code somehow slips through. (The only repo I will not allow auto-formatting on is ThreeDart. because the Dart formatting is horrible and destroys files like [Matrix4.dart](https://github.com/Grant-Nelson/ThreeDart/blob/main/lib/src/Math/Matrix4.dart))

**Comment by Grant-Nelson** [comment]
Just thought of one thing that would help; I haven't seen/looked up if there is a good way in C# to have it checkout a github repo, built the dll, and consume it. Or if there is a way proper way to commit a dll to github for a C# build to fetch it. If you know how to improve the build steps so that it doesn't require manually cloning `PatiteParser`, opening it, building the dll, then opening `Blackboard` to consume it, that would be a wonderful improvement.
